### PR TITLE
Setup IJulia in `@require` to fix dependency issue #173

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks like there's more issues than this.

**Comment by mpastell** [comment]
What do you mean by more issues?

**Comment by ChrisRackauckas** [comment]
IJulia.jupyter is no longer defined in v1.0, and `notebook` is not detected as implemented in this form.

**Comment by mpastell** [comment]
I think that is fixed in #174 , I'll combine these PRs.

**Comment by mpastell** [comment]
I fixed this in cb791e8 , so I'll close this PR.

**Pull request closed without merging**
