### PR TITLE
Add appveyor testing

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
The tests actually fail, I think that is the same problem as #65.

You also have to enable appveyor for the repo, and then add the badges etc.

**Comment by mpastell** [comment]
Thanks! This is very useful, I'll try to set it up.

**Comment by mpastell** [comment]
@davidanthoff do you know of a good way install PyPlot on appveyor? Or to detect when the test is running on appveyor and skipping certain tests? 

The tests on win64 now run fine until PyPlot is needed.

**Comment by tkelman** [comment]
Setting the environment variable `PYTHON` to empty should get PyPlot working on appveyor

**Pull request merged**
